// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type CreateResponse struct {
	Id              int64  `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type DeleteRequest struct {
	Id int64 `path:"id"`
}

type DeleteResponse struct {
	Id              int64  `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type UpdateRequest struct {
	Id              int64  `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type UpdateResponse struct {
	Id              int64  `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type GetListRequest struct {
	Page  int64 `json:"page"`
	Limit int64 `json:"limit"`
}

type GetListResponse struct {
	Id              int64  `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type GetIdRequest struct {
	Id int64 `path:"id"`
}
