// Code generated by goctl. DO NOT EDIT!
// Source: secret.proto

package server

import (
	"context"

	"github.com/tqtcloud/manage/service/secret/rpc/internal/logic"
	"github.com/tqtcloud/manage/service/secret/rpc/internal/svc"
	"github.com/tqtcloud/manage/service/secret/rpc/types/secret"
)

type SecretServer struct {
	svcCtx *svc.ServiceContext
	secret.UnimplementedSecretServer
}

func NewSecretServer(svcCtx *svc.ServiceContext) *SecretServer {
	return &SecretServer{
		svcCtx: svcCtx,
	}
}

func (s *SecretServer) SecretCreate(ctx context.Context, in *secret.CreateRequest) (*secret.CreateResponse, error) {
	l := logic.NewSecretCreateLogic(ctx, s.svcCtx)
	return l.SecretCreate(in)
}

func (s *SecretServer) SecretDelete(ctx context.Context, in *secret.DeleteRequest) (*secret.DeleteResponse, error) {
	l := logic.NewSecretDeleteLogic(ctx, s.svcCtx)
	return l.SecretDelete(in)
}

func (s *SecretServer) SecretUpdate(ctx context.Context, in *secret.UpdateRequest) (*secret.UpdateResponse, error) {
	l := logic.NewSecretUpdateLogic(ctx, s.svcCtx)
	return l.SecretUpdate(in)
}

func (s *SecretServer) SecretList(ctx context.Context, in *secret.GetListRequest) (*secret.GetListResponse, error) {
	l := logic.NewSecretListLogic(ctx, s.svcCtx)
	return l.SecretList(in)
}

func (s *SecretServer) SecretGetId(ctx context.Context, in *secret.GetIdRequest) (*secret.CreateResponse, error) {
	l := logic.NewSecretGetIdLogic(ctx, s.svcCtx)
	return l.SecretGetId(in)
}
