// Code generated by goctl. DO NOT EDIT!
// Source: operator.proto

package server

import (
	"context"

	"github.com/tqtcloud/manage/service/provider/aliyun/operator/rpc/internal/logic"
	"github.com/tqtcloud/manage/service/provider/aliyun/operator/rpc/internal/svc"
	"github.com/tqtcloud/manage/service/provider/aliyun/operator/rpc/types/operator"
)

type OperatorServer struct {
	svcCtx *svc.ServiceContext
	operator.UnimplementedOperatorServer
}

func NewOperatorServer(svcCtx *svc.ServiceContext) *OperatorServer {
	return &OperatorServer{
		svcCtx: svcCtx,
	}
}

func (s *OperatorServer) HostSync(ctx context.Context, in *operator.CreateHostRequest) (*operator.GetListResponse, error) {
	l := logic.NewHostSyncLogic(ctx, s.svcCtx)
	return l.HostSync(in)
}

func (s *OperatorServer) HostDelete(ctx context.Context, in *operator.DeleteHostRequest) (*operator.DeleteHostResponse, error) {
	l := logic.NewHostDeleteLogic(ctx, s.svcCtx)
	return l.HostDelete(in)
}

func (s *OperatorServer) HostUpdate(ctx context.Context, in *operator.CreateHostRequest) (*operator.CreateHostResponse, error) {
	l := logic.NewHostUpdateLogic(ctx, s.svcCtx)
	return l.HostUpdate(in)
}

func (s *OperatorServer) HostList(ctx context.Context, in *operator.GetListRequest) (*operator.GetListResponse, error) {
	l := logic.NewHostListLogic(ctx, s.svcCtx)
	return l.HostList(in)
}

func (s *OperatorServer) HostGetId(ctx context.Context, in *operator.GetIdHostRequest) (*operator.DeleteHostResponse, error) {
	l := logic.NewHostGetIdLogic(ctx, s.svcCtx)
	return l.HostGetId(in)
}
