CREATE TABLE IF NOT EXISTS `hosts` (
    `instance_id` varchar(64)  NOT NULL COMMENT '实例Id',
    `regionid` varchar(64)  NOT NULL COMMENT '实例所属地域ID',
    `instance_name` varchar(64)  NOT NULL COMMENT '实例名称',
    `expired_time` varchar(64)  NOT NULL COMMENT '过期时间',
    `creation_time` varchar(64)  NOT NULL COMMENT '实例创建时间',
    `keyPair_name` varchar(64)  DEFAULT NULL COMMENT '密钥对名称',
    `description` varchar(64)  DEFAULT NULL COMMENT '实例描述',
    `os_name` varchar(255) NOT NULL COMMENT '操作系统名称',
    `image_id` char(64)  NOT NULL COMMENT '镜像Id',
    `gpu_amount` tinyint(4) DEFAULT NULL COMMENT 'gpu核数',
    `cpu` tinyint(4) NOT NULL COMMENT 'cpu核数',
    `memory` int(13) NOT NULL COMMENT '内存大小',
    `os_type` varchar(255)  NOT NULL COMMENT '操作系统类型',
    `instance_type` varchar(64)  NOT NULL COMMENT '实例规格',
    `instance_charge_type` varchar(64)  NOT NULL COMMENT '实例的计费方式',
    `internet_max_bandwidth_out` int(10) NOT NULL COMMENT '外网最大出口带宽',
    `internet_max_bandwidth_in` int(10) NOT NULL COMMENT '外网最大入口带宽',
    `primaryip` varchar(64)  NOT NULL COMMENT '弹性网卡主私有IP地址',
    `publicip` varchar(64)  DEFAULT NULL COMMENT '实例的公网IP列表',
    `eip_dddresses` varchar(64)  DEFAULT NULL COMMENT '实例的弹性公网IP列表',
    `security_group_id` varchar(255)  DEFAULT NULL COMMENT '实例所属安全组Id列表',
    PRIMARY KEY (`instance_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务器主机信息';