// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Name         string `json:"name"`
	Gender       int64  `json:"gender"`
	Mobile       string `json:"mobile"`
	Email        string `json:"email"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
	Email  string `json:"email"`
}

type UserInfoResponse struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
	Email  string `json:"email"`
}

type UserListRequest struct {
	Page  int64 `form:"page"`
	Limit int64 `form:"limit"`
}

type UserListResponse struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
	Email  string `json:"email"`
}

type CreateSecretRequest struct {
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type CreateSecretResponse struct {
	Id              string `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type DeleteSecretRequest struct {
	Id string `path:"id"`
}

type DeleteSecretResponse struct {
	Id              string `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type UpdateSecretRequest struct {
	Id              string `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type UpdateSecretResponse struct {
	Id              string `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type GetSecretListRequest struct {
	Page  int64 `form:"page"`
	Limit int64 `form:"limit"`
}

type GetSecretListResponse struct {
	Id              string `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type GetSecretIdRequest struct {
	Id string `path:"id"`
}

type CreateTaskRequest struct {
	TaskName string `json:"taskname"`
	Vendor   int64  `json:"vendor"`
	TaskType int64  `json:"tasktype"`
	SecretId string `json:"secret_id"`
	Region   string `json:"region"`
}

type CreateTaskResponse struct {
	Id         string `json:"id"`
	TaskName   string `json:"taskname"`
	Vendor     string `json:"vendor"`
	TaskType   string `json:"tasktype"`
	SecretId   string `json:"secret_id"`
	Region     string `json:"secret_desc"`
	TaskUser   string `json:"taskuser"`
	Status     string `json:"status"`
	Message    string `json:"message"`
	Start_At   string `json:"start_at"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}

type DeleteTaskRequest struct {
	Id string `path:"id"`
}

type DeleteTaskResponse struct {
	Id           string `json:"id"`
	TaskName     string `json:"taskname"`
	Vendor       string `json:"vendor"`
	TaskType     string `json:"tasktype"`
	SecretId     string `json:"secret_id"`
	Region       string `json:"secret_desc"`
	TaskUser     string `json:"taskuser"`
	Status       string `json:"status"`
	Message      string `json:"message"`
	Start_At     string `json:"start_at"`
	End_At       string `json:"end_at"`
	TotalSucceed int64  `json:"total_succeed"`
	TotalFailed  int64  `json:"total_failed"`
	CreateTime   string `json:"create_time"`
	UpdateTime   string `json:"update_time"`
}

type GetTaskListRequest struct {
	Page  int64 `form:"page"`
	Limit int64 `form:"limit"`
}

type GetTaskListResponse struct {
	Id           string `json:"id"`
	TaskName     string `json:"taskname"`
	Vendor       string `json:"vendor"`
	TaskType     string `json:"tasktype"`
	SecretId     string `json:"secret_id"`
	Region       string `json:"secret_desc"`
	TaskUser     string `json:"taskuser"`
	Status       string `json:"status"`
	Message      string `json:"message"`
	Start_At     string `json:"start_at"`
	End_At       string `json:"end_at"`
	TotalSucceed int64  `json:"total_succeed"`
	TotalFailed  int64  `json:"total_failed"`
	CreateTime   string `json:"create_time"`
	UpdateTime   string `json:"update_time"`
}

type GetTaskIdRequest struct {
	Id string `path:"id"`
}

type HostResponse struct {
	InstanceId              string `json:"instance_id"`                //  实例id
	Regionid                string `json:"regionid"`                   //  实例所属地域id
	InstanceName            string `json:"instance_name"`              //  实例名称
	ExpiredTime             string `json:"expired_time"`               //  过期时间
	CreationTime            string `json:"creation_time"`              //  实例创建时间
	KeypairName             string `json:"keypair_name"`               //  密钥对名称
	Description             string `json:"description"`                //  实例描述
	OsName                  string `json:"os_name"`                    //  操作系统名称
	ImageId                 string `json:"image_id"`                   //  镜像id
	GpuAmount               int64  `json:"gpu_amount"`                 //  gpu核数
	Cpu                     int64  `json:"cpu"`                        //  cpu核数
	Memory                  int64  `json:"memory"`                     //  内存大小
	OsType                  string `json:"os_type"`                    //  操作系统类型
	InstanceType            string `json:"instance_type"`              //  实例规格
	InstanceChargeType      string `json:"instance_charge_type"`       //  实例的计费方式
	InternetMaxBandwidthOut int64  `json:"internet_max_bandwidth_out"` //  外网最大出口带宽
	InternetMaxBandwidthIn  int64  `json:"internet_max_bandwidth_in"`  //  外网最大入口带宽
	Primaryip               string `json:"primaryip"`                  //  弹性网卡主私有ip地址
	Publicip                string `json:"publicip"`                   //  实例的公网ip列表
	EipAddresses            string `json:"eip_addresses"`              //  实例的弹性公网ip列表
	SecurityGroupId         string `json:"security_group_id"`          //  实例所属安全组id列表
}

type DeleteHostRequest struct {
	Id string `path:"id"`
}

type GetHostListRequest struct {
	Page  int64 `form:"page"`
	Limit int64 `form:"limit"`
}

type GetHostIdRequest struct {
	Id string `path:"id"`
}

type UpdateHostRequest struct {
	InstanceId              string `json:"instance_id"`                //  实例id
	Regionid                string `json:"regionid"`                   //  实例所属地域id
	InstanceName            string `json:"instance_name"`              //  实例名称
	ExpiredTime             string `json:"expired_time"`               //  过期时间
	CreationTime            string `json:"creation_time"`              //  实例创建时间
	KeypairName             string `json:"keypair_name"`               //  密钥对名称
	Description             string `json:"description"`                //  实例描述
	OsName                  string `json:"os_name"`                    //  操作系统名称
	ImageId                 string `json:"image_id"`                   //  镜像id
	GpuAmount               int64  `json:"gpu_amount"`                 //  gpu核数
	Cpu                     int64  `json:"cpu"`                        //  cpu核数
	Memory                  int64  `json:"memory"`                     //  内存大小
	OsType                  string `json:"os_type"`                    //  操作系统类型
	InstanceType            string `json:"instance_type"`              //  实例规格
	InstanceChargeType      string `json:"instance_charge_type"`       //  实例的计费方式
	InternetMaxBandwidthOut int64  `json:"internet_max_bandwidth_out"` //  外网最大出口带宽
	InternetMaxBandwidthIn  int64  `json:"internet_max_bandwidth_in"`  //  外网最大入口带宽
	Primaryip               string `json:"primaryip"`                  //  弹性网卡主私有ip地址
	Publicip                string `json:"publicip"`                   //  实例的公网ip列表
	EipAddresses            string `json:"eip_addresses"`              //  实例的弹性公网ip列表
	SecurityGroupId         string `json:"security_group_id"`          //  实例所属安全组id列表
}
