// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Name         string `json:"name"`
	Gender       int64  `json:"gender"`
	Mobile       string `json:"mobile"`
	Email        string `json:"email"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
	Email  string `json:"email"`
}

type UserInfoResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
	Email  string `json:"email"`
}

type UserListRequest struct {
	Page  int64 `form:"page"`
	Limit int64 `form:"limit"`
}

type UserListResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
	Email  string `json:"email"`
}

type CreateSecretRequest struct {
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type CreateSecretResponse struct {
	Id              int64  `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type DeleteSecretRequest struct {
	Id int64 `path:"id"`
}

type DeleteSecretResponse struct {
	Id              int64  `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type UpdateSecretRequest struct {
	Id              int64  `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type UpdateSecretResponse struct {
	Id              int64  `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type GetSecretListRequest struct {
	Page  int64 `form:"page"`
	Limit int64 `form:"limit"`
}

type GetSecretListResponse struct {
	Id              int64  `json:"id"`
	Vendor          string `json:"vendor"`
	AccessKeyId     string `json:"accesskeyid"`
	AccessKeySecret string `json:"accesskeysecret"`
}

type GetSecretIdRequest struct {
	Id int64 `path:"id"`
}

type CreateTaskRequest struct {
	TaskName string `json:"taskname"`
	Vendor   int64  `json:"vendor"`
	TaskType int64  `json:"tasktype"`
	SecretId int64  `json:"secret_id"`
	Region   string `json:"region"`
	UserId   int64  `json:"userid"`
}

type CreateTaskResponse struct {
	Id         int64  `json:"id"`
	TaskName   string `json:"taskname"`
	Vendor     string `json:"vendor"`
	TaskType   string `json:"tasktype"`
	SecretId   int64  `json:"secret_id"`
	Region     string `json:"secret_desc"`
	TaskUser   string `json:"taskuser"`
	Status     string `json:"status"`
	Message    string `json:"message"`
	Start_At   string `json:"start_at"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}

type DeleteTaskRequest struct {
	Id int64 `path:"id"`
}

type DeleteTaskResponse struct {
	Id           int64  `json:"id"`
	TaskName     string `json:"taskname"`
	Vendor       string `json:"vendor"`
	TaskType     string `json:"tasktype"`
	SecretId     int64  `json:"secret_id"`
	Region       string `json:"secret_desc"`
	TaskUser     string `json:"taskuser"`
	Status       string `json:"status"`
	Message      string `json:"message"`
	Start_At     string `json:"start_at"`
	End_At       string `json:"end_at"`
	TotalSucceed int64  `json:"total_succeed"`
	TotalFailed  int64  `json:"total_failed"`
	CreateTime   string `json:"create_time"`
	UpdateTime   string `json:"update_time"`
}

type GetTaskListRequest struct {
	Page  int64 `form:"page"`
	Limit int64 `form:"limit"`
}

type GetTaskListResponse struct {
	Id           int64  `json:"id"`
	TaskName     string `json:"taskname"`
	Vendor       string `json:"vendor"`
	TaskType     string `json:"tasktype"`
	SecretId     int64  `json:"secret_id"`
	Region       string `json:"secret_desc"`
	TaskUser     string `json:"taskuser"`
	Status       string `json:"status"`
	Message      string `json:"message"`
	Start_At     string `json:"start_at"`
	End_At       string `json:"end_at"`
	TotalSucceed int64  `json:"total_succeed"`
	TotalFailed  int64  `json:"total_failed"`
	CreateTime   string `json:"create_time"`
	UpdateTime   string `json:"update_time"`
}

type GetTaskIdRequest struct {
	Id int64 `path:"id"`
}
